# MLP training overrides
ONLINE: true
N_TRAIN: 4000
N_TEST: 1000
N_SAMPLES: [1024]
width: 8192
depth: 2
bias: True
NUM_TRIALS: 2
MAX_ITER: 5000000
LR: 0.02

# Dataset hyperparameters
datasethps:
  dataset: cifar5m
  classes:
    - [0, 1, 2, 3, 4]
    - [5, 6, 7, 8, 9]
  center: true
  normalize: false
  zca_strength: 0.0
  cutoff_mode: 40000
  weight_variance: 1.0
  bias_variance: 1.0

expt_dir: hermite-eigenstructure-ansatz/mlp/cifar5m
